spring:
  config:
    import: "classpath:application-secret.yml"

  application:
    name: fraud-detection-system

server:
  port: 8080

redis:
  host: localhost
  port: 6379

jwt:
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 7