spring:
  config:
    import: "classpath:application-secret.yml"

  application:
    name: fraud-detection-system

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

redis:
  host: localhost
  port: 6379

jwt:
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 7